// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://lbldzbudozshdsqfaogx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxibGR6YnVkb3pzaGRzcWZhb2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA0MDY2MTMsImV4cCI6MjA0NTk4MjYxM30.A2CM7-Ob8I_lcK5NYL2GqgAuof7GALg8NK5lnMohSqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);